enum Status { LOADING, COMPLETED, EMPTY, ERROR }

enum AuthResponseStatus {
  SUCCESS,
  QR_INVALID,
  USER_NOT_FOUND,
  MAX_DEVICES_ERROR,
  EMAIL_ALREADY_EXISTS,
  WRONG_PASSWORD,
  CONNECTION_FAILED,
  ANOTHER_ERROR,
}
