name: sectec30_app_registro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.0.0
  http: ^0.13.3
  http_parser: ^4.0.0
  path_provider: "2.0.2"
  url_launcher: ^6.1.5
  ext_storage: any
  signature: ^5.0.0
  image_picker: "0.8.5"
  mime_type: ^0.3.2
  permission_handler: "10.2.0"
  lottie: ^1.4.1
  flutter_credit_card: ^0.1.3
  provider: ^6.0.3
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.6.3
  firebase_messaging: ^12.0.2
  location: ^4.2.0
  google_fonts: ^3.0.1
  dio:
  barcode_scan2: ^4.1.4
  shared_preferences: ^2.0.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  qr_code_tools: ^0.0.7
  another_flushbar: ^1.10.23
  pdf: ^2.1.0
  pdf_viewer_plugin: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.2.43-beta
  share_plus: ^4.0.10+1
  flutter_local_notifications: ^9.7.0
  paginate_firestore: ^1.0.3+1
  downloads_path_provider_28: ^0.1.2
  open_file_safe: ^3.2.3
  modal_bottom_sheet: ^2.0.0
  table_calendar: ^3.0.3
  intl: ^0.17.0
  device_info_plus: ^3.2.1
  syncfusion_flutter_calendar: ^19.4.48
  animated_check: ^1.0.5
  settings_ui: ^2.0.2
  flutter_geofence: ^0.4.4
  camera: ^0.10.0
  loading_indicator: ^3.1.0
  google_mlkit_face_detection: ^0.4.0
  barcode_widget: ^1.5.0
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.5
dev_dependencies:
  flutter_test:
    sdk: flutter
    
dependency_overrides:
  syncfusion_flutter_core: ^20.2.43
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/credencial/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
